global:
  scrape_interval:     10s  
  evaluation_interval: 10s
  external_labels:
    monitor: 'mtail-monitor'

rule_files:
#  - "/var/app/prometheus/alert.rules"

scrape_configs:
  - job_name: 'mtail'
    static_configs:
      - targets:
        - 'mtail:3903'
